services:
- type: web
  name: outline
  env: docker
  branch: master
  envVars:
    #this has specific rules around it that can't be generated
  - key: SECRET_KEY
    sync: false
  - key: UTILS_SECRET
    generateValue: true
  - key: REDIS_URL
    fromService:
      name: redis
      type: pserv
      property: hostport
  - key: DATABASE_URL
    fromDatabase:
      name: outline-db
      property: connectionString
  - key: DATABASE_URL_TEST
    fromDatabase:
      name: outline-db
      property: connectionString
  - key: URL
    sync: false
  - key: AWS_ACCESS_KEY_ID
    sync: false
  - key: AWS_SECRET_ACCESS_KEY
    sync: false
  - key: AWS_REGION
    sync: false
  - key: AWS_S3_UPLOAD_BUCKET_NAME
    sync: false
  - key: AWS_S3_UPLOAD_BUCKET_URL
    sync: false
  - key: AWS_S3_UPLOAD_MAX_SIZE
    value: 26214400
  - key: AWS_S3_FORCE_PATH_STYLE
    value: true
  - key: AWS_S3_ACL
    value: private
  - key: SLACK_KEY
    sync: false
  - key: SLACK_SECRET
    sync: false
  - key: SLACK_VERIFICATION_TOKEN
    sync: false
  - key: SLACK_APP_ID
    sync: false
  - key: SLACK_MESSAGE_ACTIONS
    value: true
  - key: TEAM_LOGO
    sync: false
  - key: SMTP_USERNAME
    sync: false
  - key: SMTP_PASSWORD
    sync: false
  - key: SMTP_HOST
    sync: false
  - key: SMTP_PORT
    sync: false
  - key: SMTP_FROM_EMAIL
    sync: false
  - key: SENTRY_DSN
    sync: false
- type: pserv
  name: outline-redis
  env: docker
  repo: https://github.com/render-examples/redis.git # optional
  envVars:
  - key: GENERATED_SECRET
    generateValue: true
  - key: DASHBOARD_SECRET
    sync: false
  disk:
    name: redis-data
    mountPath: /var/lib/redis


# GOOGLE_ANALYTICS_ID=
# SMTP_REPLY_EMAIL=
# Custom logo that displays on the authentication screen, scaled to height: 60px



databases:
    - name: outline-db
      databaseName: outline # optional (Render may add a suffix)
      ipAllowList: [] # optional (defaults to allow all)
